### ISSUE TITLE
Reviewing

### ISSUE THREAD

**Issue by Tyst** [artingo/Game#1]
Hi Fred,

We are in the process of reviewing your application.  Apologies for the delay in response; there were some extenuating family-circumstances I had to tend to over the past two weeks.

Thanks for the submission, we'll be in touch.  :)

**Comment by artingo** [comment]
Hello Carl,my condolences for your loss. :-(I totally understand the reason for delay.I was on holiday with my kids for the past two weeks and used the last weekend to continue implementing the game. The principal mechanics already work but I would like to finalize it today and tomorrow evening.You can try it live on my webserver: http://artingo.de/game/jGame.htmlInstruction:When you click on a banana, the upper or lower teams scores and a new objective is spawned after 10 seconds. When one team has more than 10 points, it wins.You can reach me via Skype on: office@artingo.deBest regards,Fred Walther


-------- Original Message --------
Subject: [Game] Reviewing (#1)

**Comment by artingo** [comment]
Hi Carl,
I just commited my last changes. The game is playable now. You can testdrive it here:
http://artingo.de/game/jGame.html

You can contact me directly via email, if you want.
alfred.walther@artingo.de

Best regards.
Fred

**Comment by artingo** [comment]
Closed a long time ago...
